version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    target-branch: "master"
    labels:
      - "dependencies"
      - "github-actions"

  # UV (Python package manager)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"  
      time: "03:30"
    target-branch: "master"
    labels:
      - "dependencies"
      - "python"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 10