name: Lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup UV
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.11'

      - name: Cache UV
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}

      - name: Sync dependencies (dev)
        run: uv sync --dev

      - name: Python syntax compile check
        run: make compile-check

      - name: Display Ruff version
        run: uv run ruff --version

      - name: Run Ruff linter
        run: uv run ruff check .

      - name: Run Ruff formatter check
        run: uv run ruff format --check .
